export const linksForRoot=[{
    id:0,
    name:'react'
  },{
    id:1,
    name:'react-dom'
  }]
  export const topics ={
    0:{
        id:0,
        title:'(Root)',
        childIds:[1]
    },
    1:{
        id:1,
        title:'react',
        childIds:[2]
    },
    2:{
        id:2,
        title:'hooks',
        childIds:[3,4]
    },
    3:{
        id:3,
        title:'useTransition',
        childIds:[]
    },
    4:{
        id:4,
        title:'useDeferredValue',
        childIds:[]
    }
  }